'use strict';
/*
  REUSABLE CONTENT MODEL
  Replace the CHAPTERS data to use this layout with another subject.
  Chapter: id, label, title, description, steps, topics.
  Topic: id, label, heading, paragraphs, mechanism, connection, step.
  Layout, routing, search, navigation and mobile behavior are separate from the copy.
  Copy is local trusted content; escapeHtml protects inserted strings.
  No framework, account, API key, build system, font CDN or internet is needed.
*/
const CHAPTERS = [
 {id:'energy',label:'The energy',short:'Energy',title:'Start small. Follow the energy.',description:'One question at a time, from the basic idea to the mechanism.',
 steps:[{label:'FUEL',icon:'fuel',caption:'<strong>Fuel is the starting point.</strong> Explore what is available before asking how it becomes useful.'},{label:'ATP',icon:'atp',caption:'<strong>ATP connects energy to work.</strong> A small molecule sits between available fuel and the work of contraction.'},{label:'WORK',icon:'work',caption:'<strong>Work is the outcome.</strong> The next question is how a chemical process becomes a mechanical one.'}],
 topics:[
 {id:'overview',label:'The big picture',heading:'Fuel is not the final step.',paragraphs:['A muscle does not use food directly. Start with ATP: the molecule that connects chemical energy with the work of contraction.','Follow that connection first. Then add the signal, the movement, and the challenge of keeping it all going.'],mechanism:['This is the space for the technical explanation. The finished article can explain the energy transfer with one clear sequence and a supporting reference.','The main reading path stays short. Detail remains available without interrupting it.'],connection:['Energy gives us the first piece. The next chapter asks what tells the muscle to act.'],step:1},
 {id:'atp',label:'ATP, explained',heading:'A small molecule. A useful link.',paragraphs:['ATP links chemical reactions to cellular work. Here, the reader can move from the familiar idea of energy to a more precise mechanism.','Keep the essential point visible. Put molecular detail and terminology one level deeper.'],mechanism:['In the finished article, this topic would introduce ATP, ADP, and phosphate with an annotated diagram.','This placeholder demonstrates where a precise explanation, a definition, and its source would sit.'],connection:['Knowing what supplies the energy is only the beginning. The muscle also needs a signal and a mechanism.'],step:1},
 {id:'cycle',label:'A continuous cycle',heading:'Keep rebuilding. Keep moving.',paragraphs:['The supply has to keep up with the work. This topic connects the molecule to a process that continues throughout an effort.','The same layout can hold a short loop, a comparison, or an interactive example without adding a new page design.'],mechanism:['A developed version could show a simple ATP–ADP cycle. Labels would explain what is used and what is regenerated.','This example is about the reading structure; it does not calculate energy availability or exercise performance.'],connection:['The regeneration chapter will return to this cycle from the supply side.'],step:0}
 ]},
 {id:'signal',label:'The signal',short:'Signal',title:'Energy is available. What starts the action?',description:'Follow the instruction from a signal to a response.',
 steps:[{label:'SIGNAL',icon:'signal',caption:'<strong>A signal begins the sequence.</strong> This first step introduces the instruction.'},{label:'LINK',icon:'link',caption:'<strong>One event enables another.</strong> Each link gets its own explanation instead of a crowded diagram.'},{label:'RESPONSE',icon:'work',caption:'<strong>The muscle responds.</strong> Follow the sequence into the next chapter.'}],
 topics:[
 {id:'overview',label:'The big picture',heading:'Energy alone is not an instruction.',paragraphs:['This chapter introduces a second layer: the signal that coordinates the muscle’s response.','The reader follows a simple sequence first. The detailed explanation can then identify the structures involved.'],mechanism:['The full article could follow the nerve signal, the muscle membrane, and calcium release.','Each label should explain one link in the sequence. A reference belongs beside the detailed explanation.'],connection:['The signal connects available energy to the machinery that produces force.'],step:0},
 {id:'sequence',label:'The sequence',heading:'Give each step a clear role.',paragraphs:['A complex mechanism becomes easier to explore when each step answers one question.','Here, the reader can select a stage in the visual and keep the explanation in the same place.'],mechanism:['This is a placeholder for the ordered mechanism. A final version could add short animations with explicit play and pause controls.'],connection:['The next question is no longer when to act, but how the movement is produced.'],step:1},
 {id:'coordination',label:'Coordination',heading:'From a local event to a response.',paragraphs:['Use this topic to connect the individual steps rather than repeat them.','The section ends by showing why the next part of the story matters.'],mechanism:['Add only the definitions and supporting evidence needed to connect the signal to contraction.'],connection:['The movement chapter zooms in on the machinery.'],step:2}
 ]},
 {id:'movement',label:'The movement',short:'Movement',title:'From a small interaction to visible force.',description:'Zoom in on the mechanism, then step back to see the result.',
 steps:[{label:'INTERACT',icon:'link',caption:'<strong>Begin with the interaction.</strong> Show the small event before scaling it up.'},{label:'REPEAT',icon:'cycle',caption:'<strong>Repeat the process.</strong> A cycle needs a beginning, a change, and a reset.'},{label:'MOVEMENT',icon:'work',caption:'<strong>Step back to the result.</strong> Connect the mechanism to something the reader recognizes.'}],
 topics:[
 {id:'overview',label:'The big picture',heading:'Small actions. A larger result.',paragraphs:['This is the place to connect the molecular explanation with a muscle doing work.','Show one useful interaction, then explain what changes when the process is repeated.'],mechanism:['The finished explanation can introduce actin, myosin, and the repeating structure of a muscle fiber.','An annotated visual is more useful here than a decorative illustration.'],connection:['A mechanism that repeats also needs to be supplied repeatedly.'],step:0},
 {id:'cycle',label:'The mechanism',heading:'Show the cycle, not a wall of text.',paragraphs:['Break the mechanism into a few meaningful stages. Let the reader move between them without scrolling away from the diagram.','The current visual is deliberately conceptual. Its role is to test the interaction before building a scientific illustration.'],mechanism:['Add a precise explanation of the contraction cycle here, with each stage matched to the visual and checked against a primary reference.'],connection:['The next chapter follows the supply side of the same process.'],step:1},
 {id:'scale',label:'Changing scale',heading:'Keep the connection visible.',paragraphs:['Moving from molecule to muscle changes the scale of the explanation. It should not feel like starting a different article.','Use a short transition to show what stays the same and what becomes visible at the next level.'],mechanism:['A later visual could let the reader switch between a molecular view, a muscle fiber, and the whole muscle.'],connection:['The larger result brings us back to the continuous demand for energy.'],step:2}
 ]},
 {id:'supply',label:'The supply',short:'Supply',title:'The work continues. So must the supply.',description:'Connect a repeating process to the resources that support it.',
 steps:[{label:'RESOURCES',icon:'fuel',caption:'<strong>Start with the inputs.</strong> Introduce the resources relevant to the explanation.'},{label:'REBUILD',icon:'cycle',caption:'<strong>Follow the regeneration.</strong> Connect supply with the cycle introduced in chapter one.'},{label:'DEMAND',icon:'atp',caption:'<strong>Return to the work.</strong> Keep production and consumption in the same picture.'}],
 topics:[
 {id:'overview',label:'The big picture',heading:'A process, not a one-off event.',paragraphs:['Return to ATP with a different question: how does the supply continue while the muscle is working?','Use this chapter to connect the earlier mechanism to the larger system, without adding every detail at once.'],mechanism:['The final article can compare the pathways that regenerate ATP. Each pathway would need a clear role, a boundary, and a supporting reference.'],connection:['Maintaining supply becomes more demanding when the conditions change.'],step:1},
 {id:'pathways',label:'The pathways',heading:'Compare only what matters.',paragraphs:['A comparison works best when every item answers the same questions.','This topic could compare the pathways using a small set of shared labels rather than a dense table.'],mechanism:['Potential comparison fields: what the pathway uses, how it contributes, and what constrains it. Final wording and values need review.'],connection:['The comparison should lead back to the body as one connected system.'],step:0},
 {id:'balance',label:'Supply and demand',heading:'Keep both sides in view.',paragraphs:['One side of the story is the work being done. The other is the process that supports it.','Use the same visual space to explore that relationship, with no invented performance numbers.'],mechanism:['A later interactive model could be added here only after its assumptions, units, and limitations are defined.'],connection:['The last chapter asks what happens as the constraints accumulate.'],step:2}
 ]},
 {id:'limits',label:'The limits',short:'Limits',title:'What makes the same task harder?',description:'Bring the parts together without reducing the answer to a single cause.',
 steps:[{label:'DEMAND',icon:'atp',caption:'<strong>The task places demands on the system.</strong> Start with what the body is trying to sustain.'},{label:'CONSTRAINTS',icon:'signal',caption:'<strong>The conditions change.</strong> Explore the relevant limits one at a time.'},{label:'RESPONSE',icon:'cycle',caption:'<strong>The system responds.</strong> Connect the changing conditions to the next decision.'}],
 topics:[
 {id:'overview',label:'The big picture',heading:'The parts do not work in isolation.',paragraphs:['This chapter brings energy, signaling, movement, and supply back into the same picture.','The goal is to explain a connection, not to overload the reader with a list of everything that can change.'],mechanism:['Use the detailed layer to examine one constraint at a time, with clear evidence and appropriate uncertainty.'],connection:['Return to the first chapter with a fuller picture of the process.'],step:1},
 {id:'constraints',label:'The constraints',heading:'Explore one limit at a time.',paragraphs:['Each constraint can become a topic with the same reading structure: the idea, a visual, and optional detail.','That makes the page expandable without making its first screen more complicated.'],mechanism:['This is where a final article could discuss specific constraints. Examples and claims should be selected and validated during content development.'],connection:['The conclusion can now connect the constraints without presenting a single universal explanation.'],step:1},
 {id:'whole',label:'The whole system',heading:'End with the connection.',paragraphs:['The final topic should give the reader a clearer view of the whole system, not another collection of details.','A short conclusion can link back to the opening question and offer a natural route into further reading.'],mechanism:['Use this area for sources, definitions, remaining uncertainties, or the boundaries of the explanation.'],connection:['This is the end of the layout example. Return to the first chapter, use search, or try Focus view.'],step:2}
 ]}
];
